PousseDeBambin/Controllers/ProspectController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PousseDeBambin.Models;
using System.Data.Entity.Validation;

namespace PousseDeBambin.Controllers
{
    [Authorize(Roles="Admin")]
    public class ProspectController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        //
        // GET: /Prospect/

        public ActionResult Index()
        {
            return View(db.Prospects.ToList());
        }

        //
        // GET: /Prospect/Details/5

        public ActionResult Details(int id = 0)
        {
            Prospect prospect = db.Prospects.Find(id);
            if (prospect == null)
            {
                return RedirectToAction("NotFound", "Error");
            }
            return View(prospect);
        }

        //
        // GET: /Prospect/Create
        
        [AllowAnonymous]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Prospect/Create

        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Prospect prospect)
        {
            if (ModelState.IsValid)
            {
                db.Prospects.Add(prospect);

                db.SaveChanges();

                TempData["Success"] = "Merci pour votre commentaire ! Nous ne manquerons pas de vous recontacter ;)";
                return RedirectToAction("Index", "Home", null);
            }

            return View(prospect);
        }

        //
        // GET: /Prospect/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Prospect prospect = db.Prospects.Find(id);
            if (prospect == null)
            {
                return RedirectToAction("NotFound", "Error");
            }
            return View(prospect);
        }

        //
        // POST: /Prospect/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Prospect prospect)
        {
            if (ModelState.IsValid)
            {
                db.Entry(prospect).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(prospect);
        }

        //
        // GET: /Prospect/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Prospect prospect = db.Prospects.Find(id);
            if (prospect == null)
            {
                return RedirectToAction("NotFound", "Error");
            }
            return View(prospect);
        }

        //
        // POST: /Prospect/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Prospect prospect = db.Prospects.Find(id);
            db.Prospects.Remove(prospect);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

PousseDeBambin/Views/Shared/WhoAreWe.cshtml
@{
    ViewBag.Title = "Qui sommes nous ?";
}
<div class="who_we_are">
    <div class="photos">
        <div class="photoremi"></div>
        <div class="photomarion"></div>
    </div>
    <div class="who_we_are_text">
        <h2 class="who_we_are_title">Qui sommes nous ?</h2>
        <p>Rémi et Marion travaillent tous les deux sur le projet <span class="name">Pousse De Bambin.</span></p>
        <p>Rémi est diplômé de l'école d'ingénieur en développement logiciel de <a href="http://www.cpe.fr/" target="_blank">CPE Lyon</a>.</p>
        <p>Marion est diplômée de l'école Supérieure d'Infographie <a href="http://www.ecolearies.fr/" target="_blank">ARIES</a>.</p>
        <p>
            <br />Après plusieurs participations à des listes de naissance, pour leurs proches, il leur est apparu, à tous les deux, qu'il manquait quelque chose de plus original, plus proche,
            et plus innovant qu'une simple liste sur laquelle mettre des objets. C'est ainsi qu'est né <span class="name">Pousse De Bambin</span> !
        </p>
        <p>"On espère que vous aurez autant de plaisir à utiliser <span class="name">Pousse De Bambin</span> que nous en avons à le créer !"</p>
        <p><br />Rémi et Marion</p>
    </div>
</div>

<div class="who_we_are_line"></div>

<div class="who_we_are_follow">
    <div class="photos_follow">
        <div class="photomarjorie"></div>
    </div>
    <div class="who_we_are_text">
        <h2 class="who_we_are_title">Autres collaborateurs</h2>
        <p>Marjorie a rejoint l’équipe Pousse De Bambin au poste de Webdesigner stagiaire pour une durée de 3 mois.</p>
        <p>Elle est actuellement en fin de deuxième année de classe préparatoire intégrée, à l'<a href="http://www.4mm.fr/" target="_blank">Institut G4 de Lyon</a>, en Multimédia/Management.</p>        
    </div>
    <div class="photos_follow">
        <div class="photomichael"></div>
    </div>
    <div class="who_we_are_text">        
        <p>Michaël intègre l’équipe Pousse De Bambin au poste de Directeur Marketing et Commercial.</p>
        <p>Il est diplômé du Groupe <a href="http://www.inseec.com" target="_blank">INSEEC</a> avec un Master 2 en Marketing de l’innovation.</p>        
    </div>
</div>

PousseDeBambin/Views/Shared/_AlertMessages.cshtml
<div class="indexMessages">
    @if (ViewBag.Success != null)
    {
        <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <a href="#" class="alert-link">@ViewBag.Success</a>
        </div>
    }

    @if (ViewBag.Info != null)
    {
        <div class="alert alert-info alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <a href="#" class="alert-link">@ViewBag.Info</a>
        </div>
    }

    @if (ViewBag.Warning != null)
    {
        <div class="alert alert-warning alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <a href="#" class="alert-link">@ViewBag.Warning</a>
        </div>
    }

    @if (ViewBag.Error != null)
    {
        <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <a href="#" class="alert-link">@ViewBag.Error</a>
        </div>
    }
</div>

PousseDeBambin/Views/Shared/_BaseLine.cshtml
<div id="baselineDiv">
    <h1 class="text-center">Pousse De Bambin</h1>
    <h2 class="text-center">Votre liste de naissance en 3 clics !</h2>
</div>

PousseDeBambin/Views/Shared/_ConnectedMenu.cshtml
@model PousseDeBambin.Models.ApplicationUser

<div class="barre_connexion">
    <!-- Single button -->

    <div class="dropdown-menu">
        <p>Bienvenue, @Model.UserName</p>
        <ul role="menu">
            <!-- TODO: Récupérer le lien vers la liste si il n'y en a qu'une, sinon récupérer
            tous les liens de la liste et construire un dropright
            -->
            @if (Model != null && Model.Lists != null && Model.Lists.Count != 0)
            {
                if (Model.Lists.Count == 1)
                {
                    <li><a href="@Url.Action("Manage", "List", new { id = Model.Lists.First().ListId })">Ma liste de naissance</a></li>
                }
                else if (Model.Lists.Count > 1)
                {
                    <li class="dropdown-menu">
                        <a href="#">Mes listes de naissance</a>
                        <ul>
                            @foreach (PousseDeBambin.Models.List liste in Model.Lists)
                            {
                                var url = Url.Action("Manage", "List", new { id = liste.ListId });
                                <li><a href=@url>@liste.Name</a></li>
                            }
                        </ul>
                    </li>
                }
            }

            <li><a href="@Url.Action("Manage", "Account")">Mon compte</a></li>
            <li><a href="@Url.Action("LogOffGet", "Account")">Déconnexion</a></li>
        </ul>
    </div>

</div>

<script>
    $(document).ready(function () {
        $(document).on('click', '.dropdown-menu', function () {
            $(this).toggleClass('dm-focus');
        });
    });
</script>

PousseDeBambin/Views/Shared/_ConnexionBar.cshtml
@model PousseDeBambin.Models.LoginViewModel

@{
    Layout = null;
}

<div class="barre_connexion">
    <!-- Si l'utilisateur n'est pas identifié, on affiche un formulaire de login + register -->
    @using (Html.BeginForm("LoginBar", "Account", new { returnUrl = ViewBag.ReturnUrl }, FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary("", new { @class = "validationConnexionBar" })

        <div class="form-group">
            @Html.TextBoxFor(m => m.UserName, new { @class = "form-control", placeholder = " Nom d'utilisateur" })
        </div>
        <div class="form-group">
            @Html.PasswordFor(m => m.Password, new { @class = "form-control", placeholder = " Mot de passe" })
        </div>
        <div class="form-group">
            <div class="col-md-offset-2">
                <!--<img id="searchAjaxLoading" class="ajaxLoadingGift" src="/Content/img/loading/ajax-loader.gif" alt="Loading"
                     style="display: none"/>-->
                <input type="submit" id="submitLogin" value="Se connecter" class="btn btn-default" />
            </div>
        </div>
    }
</div>

<script type="text/javascript">
    function beginLogin() {
        $("#submitLogin").attr("value", "Connexion en cours...");
        $("#submitLogin").prop('disabled', true);
    }
</script>

PousseDeBambin/Views/Shared/_Footer.cshtml
<!-- Liens verticaux + Texte aligné à droite et justifié -->
<div class="row" id="endFooter">
    <div id="liensFooter" class="container">
        <div class="row">
            <div class="element">
                @Html.ActionLink("Aide", "Help", "Miscellaneous", null, null)
            </div>
            <div class="element">
                @Html.ActionLink("Mentions légales", "LegalMentions", "Miscellaneous", null, null)
            </div>
            <!--
            <div class="element">
                @Html.ActionLink("Contact", "Create", "Prospect", null, null)
            </div>
            -->
            <div class="element">
                @Html.ActionLink("CGU", "CGU", "Miscellaneous", null, null)
            </div>
            <div class="element">
                @Html.ActionLink("Plan du site", "WebSitePlan", "Miscellaneous", null, null)
            </div>
            <div class="fb-like" data-href="https://www.facebook.com/poussedebambin" data-colorscheme="dark" data-layout="button_count" data-action="like" data-show-faces="false" data-share="true"></div>
            <a href="https://twitter.com/PoussedeBambin" class="twitter-follow-button" data-show-count="false" data-lang="fr">Follow @@PousseDeBambin</a>
            
            <div class="g-plusone" data-size="small"><div class="googleplus"></div>
            
        </div>
    </div>
</div>

PousseDeBambin/Views/Shared/_HowItWorks.cshtml
<div class="howItWorks_main">
    <div class="panel-heading">

        <!--<p class="marche">Comment ça marche ?</p>-->
        <div id="content_scrolling_text">

            <ul class="scrolling_text">
                <li class="item1">
                    <a href="#" style="text-decoration:none;"><p class="marche">Comment ça marche ?</p></a>
                    <ul>
                        <div class="text_intro">
                            <p>
                                <h3 class="title_text_intro">1- Pourquoi créer une liste de naissance sur internet ?</h3>                                  <br />
                                    Vous  attendez un heureux événement, vos proches commencent à vous solliciter pour des idées de cadeaux, la grossesse ne vous donne pas la force de courir dans les magasins… alors créer votre liste de naissance sur le web ! Un moyen simple de vous faire gagner du temps, en évitant les doublons et surtout en vous permettant de recevoir les cadeaux que vous désirez et qui vous seront utiles. Sur internet vous avez accès à des milliers d’idées de cadeaux à des prix attractifs, vos proches vont ainsi pouvoir vous gâter sans se ruiner.
                                    L’intérêt ? Arriver au jour de l’accouchement pleine d’énergie et accueillir votre bébé sereinement !

                            </p>
                            <p>
                                <h3 class="title_text_intro">2-  Pourquoi créer votre liste de naissance avec Pousse de Bambin ?</h3> 
                                    Pousse de Bambin met tous les éléments à votre disposition pour créer votre liste de naissance simplement et gratuitement ! Nous vous proposons un univers unique pour un événement unique. Pousse de Bambin vous permet, en quelques clics, de créer votre liste et de la partager instantanément  avec vos proches. Vous avez remarqué des éléments pour une chambre bébé, une poussette ou simplement un biberon sur différents sites marchands tels que Autour de bébé, Aubert… ? Pas de problème ! Sélectionnez, ajoutez et partagez, c’est aussi simple que cela chez Pousse de Bambin !
                            </p>
                            <p>
                                <h3 class="title_text_intro">3-  Quand créer sa liste de naissance ?</h3> 
                                    Généralement les futurs parents le font pendant la grossesse et attendent la deuxième échographie pour connaitre le sexe de bébé. Cela vous permettra de choisir entre une poussette bleue, une chambre bébé rose ou un biberon vert… Néanmoins vous êtes libre de créer votre liste quand bon vous semble, le faire en début de grossesse peut aussi vous permettre d’aiguiller rapidement vos proches vers les idées cadeaux que vous aimez…
                            </p>
                            <p>
                                <h3 class="title_text_intro">4- Comment créer sa liste de naissance ?</h3> 
                                    C’est très simple ! Rendez-vous sur la page d’accueil de <a href="www.poussedebambin.com" class="link_scrolling_text">Pousse de Bambin</a> et allez directement sur «<a href="http://www.poussedebambin.com/List/Creation" class="link_scrolling_text"> je crée ma liste </a>» puis allez sélectionner les idées cadeaux préalablement vues sur les  sites marchands (Autour de bébé, Bébé 9, Aubert…), venez les ajouter à votre liste et une fois que celle-ci sera complète, n’oubliez surtout pas de la valider ! Une fois validée, il ne vous reste plus qu’à la partager avec vos proches.
</p>
                            <p>
                                <h3 class="title_text_intro">5- Que puis-je mettre dans ma liste de naissance ?</h3> 
                                    De la chambre de bébé, à la poussette en passant par le hochet, Pousse de Bambin vous permet de constituer une liste complète répondant à tous vos besoins de futurs parents. Tout pour préparer sereinement la venue de bébé, du premier jour de grossesse à l’accouchement.
                            </p>
                            <p>
                                <h3 class="title_text_intro">6- Comment communiquer ma liste de naissance ?</h3> 
                                    Mieux que le traditionnel faire-part de naissance, prévenez votre famille et vos amis en un clic sur les réseaux sociaux ! Un message leur sera envoyé directement pour les prévenir que votre liste est disponible sur Pousse de Bambin. Tout est centralisé sur Pousse de Bambin pour leur simplifier la vie et leur faire gagnr du temps !
                            </p>
                            <div class="sign">L'équipe Pousse de Bambin...<img src="/Content/img/home/plume.png" width="31" height="56"></div>
                        </div>
                    </ul>
                </li>
            </ul>

        </div>
        <!--<div id="enSavoirPlusFooter" class="col-md-6">
            @Html.ActionLink("En savoir plus...", "Help", "Miscellanous", null, null)
        </div>-->

    </div>
    <div class="panel-body">
        <div class="step step1">

            <p class="numberHowItWorks">ÉTAPE 1</p>

            <p class="howItWorksText">

                Je crée ma liste <br />
                de naissance<br />
                gratuitement, en quelques clics

            </p>
        </div>
        <div class="step step2">

            <p class="numberHowItWorks">ÉTAPE 2</p>

            <p class="howItWorksText">

                J'ajoute les articles<br />
                de mon choix parmi toutes<br />
                les enseignes

            </p>
        </div>
        <div class="step step3">

            <p class="numberHowItWorks">ÉTAPE 3</p>

            <p class="howItWorksText">

                Je partage facilement ma liste<br />
                de naissance avec mes <br />
                proches

            </p>
        </div>
    </div>
</div>




<!--------------------------Script texte déroulant----------------------->
<script type="text/javascript">
	$(function() {
	    var scrolling_text_ul = $('.scrolling_text > li > ul'),
	           scrolling_text_a = $('.scrolling_text > li > a');

	    scrolling_text_ul.hide();

	    scrolling_text_a.click(function (e) {
	        e.preventDefault();
	        if(!$(this).hasClass('active')) {
	            scrolling_text_a.removeClass('active');
	            scrolling_text_ul.filter(':visible').slideUp('normal');
	            // $(".text_intro").css({'margin-top':'-50px'});

	            $(this).addClass('active').next().stop(true,true).slideDown('normal');
	        } else {
	            $(this).removeClass('active');
	            $(this).next().stop(true,true).slideUp('normal');
	        }
	    });

	});
</script>

PousseDeBambin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://ogp.me/ns#"
      xmlns:fb="http://www.facebook.com/2008/fbml"
      lang="fr"
      itemscope itemtype="http://schema.org/Product">
<head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb#">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <title>@ViewBag.Title - Pousse De Bambin !</title>
    <link href="@HttpContext.Current.Request.Url.GetLeftPart(UriPartial.Authority)@Url.Content("~/Content/img/home/favicon.jpg")" rel="shortcut icon" type="image/jpeg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!--<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">-->
    @Styles.Render("~/Styles/css")
    @Scripts.Render("~/bundles/modernizr")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/carousel")

    @Scripts.Render("~/bundles/bootstrap")

    @Scripts.Render("~/bundles/star")

    @RenderSection("scripts", required: false)
    <link rel="image_src" href="@HttpContext.Current.Request.Url.GetLeftPart(UriPartial.Authority)@Url.Content("~/Content/img/home/logo.png")" />

    <meta name="og:title" content="@ViewBag.Title - Pousse De Bambin !" />
    <meta property="og:image" content="@HttpContext.Current.Request.Url.GetLeftPart(UriPartial.Authority)@Url.Content("~/Content/img/home/logo.png")" />
    <meta name="og:description" content="@ViewBag.Description" />
    <meta name="og:url" content="@HttpContext.Current.Request.Url.AbsoluteUri" />
    <meta name="fb:app_id" content="708244749188733" />
    <meta name="site_name" content="Pousse De Bambin" />

    @RenderSection("metaDescription", required: false)

    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
            m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-47337807-1', 'poussedebambin.com');
        ga('require', 'displayfeatures');
        ga('send', 'pageview');
    </script>
</head>
<body>
    @*@Html.Partial("_MessageBeta")*@
    <header>
        <div id="connexionBar" class="connexionBar">
            @Html.Action("LoginBar", "Account", new { returnUrl = ViewContext.HttpContext.Request.Url.PathAndQuery })
        </div>
        <!-- @Html.Partial("_BaseLine") -->
        @Html.Partial("_MainTabs")
    </header>
    <!--d
    </header>
    <!--div class="alert alert-success">
        <p id="textBeta">
            Pousse De Bambin vient de naître...et, comme tout être, va se perfectionner petit à petit. Ainsi
            <a href="mailto:remi@poussedebambin.com?subject=Retour Pousse De Bambin&cc=marion@poussedebambin.com&body=Bonjour," target="_blank" class="alert-link">contactez nous</a> pour faire votre retour ! Vous ferez une pousse heureux !
        </p>
    </div>-->
    <div class="">

        <div id="contentAndFooter" class="">
            <div id="body">
                @RenderSection("breadCrumbs", required: false)
                @RenderSection("featured", required: false)
                <section id="mainSection">
                    <!-- Messages d'alerte divers-->
                    @Html.Partial("_AlertMessages")
                    @RenderBody()
                </section>
            </div>
            <footer>
                @RenderSection("howItWorks", required: false)
                @Html.Partial("_Footer")
                @RenderSection("moreFooter", required: false)
            </footer>
        </div>
    </div>

    <!-- Viglink -->
    <script type="text/javascript">
        var vglnk = {
            api_url: '//api.viglink.com/api',
            key: 'e1280bc713785a94c14090e0302a9ab4'
        };

        (function (d, t) {
            var s = d.createElement(t); s.type = 'text/javascript'; s.async = true;
            s.src = ('https:' == document.location.protocol ? vglnk.api_url :
                     '//cdn.viglink.com/api') + '/vglnk.js';
            var r = d.getElementsByTagName(t)[0]; r.parentNode.insertBefore(s, r);
        }(document, 'script'));
    </script>
    <!-- Social script -->
    <div id="fb-root"></div>
    <script>
        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/fr_FR/all.js#xfbml=1&appId=708244749188733";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));

        !function (d, s, id) { var js, fjs = d.getElementsByTagName(s)[0]; if (!d.getElementById(id)) { js = d.createElement(s); js.id = id; js.src = "//platform.twitter.com/widgets.js"; fjs.parentNode.insertBefore(js, fjs); } }(document, "script", "twitter-wjs");

        (function () {
            var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
            po.src = 'https://apis.google.com/js/plusone.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
        })();
    </script>
    <!-- Fin Social script -->
    <!--<script type="text/javascript" src="http://s.skimresources.com/js/59995X1382328.skimlinks.js"></script>-->
    <!--Start of Zopim Live Chat Script-->
    <script type="text/javascript">
        window.$zopim || (function (d, s) {
            var z = $zopim = function (c) { z._.push(c) }, $ = z.s =
            d.createElement(s), e = d.getElementsByTagName(s)[0]; z.set = function (o) {
                z.set.
                _.push(o)
            }; z._ = []; z.set._ = []; $.async = !0; $.setAttribute('charset', 'utf-8');
            $.src = '//v2.zopim.com/?20Uq0MlI5gaqTXNATK08VGITdjo9IAHa'; z.t = +new Date; $.
            type = 'text/javascript'; e.parentNode.insertBefore($, e)
        })(document, 'script');
    </script>

    <!-- Code Google de la balise de remarketing -->
    <!--------------------------------------------------
    Les balises de remarketing ne peuvent pas être associées aux informations personnelles ou placées sur des pages liées aux catégories à caractère sensible. Pour comprendre et savoir comment configurer la balise, rendez-vous sur la page http://google.com/ads/remarketingsetup.
    --------------------------------------------------->
    <script type="text/javascript">
        /* <![CDATA[ */
        var google_conversion_id = 967658191;
        var google_custom_params = window.google_tag_params;
        var google_remarketing_only = true;
        /* ]]> */
    </script>
    <script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
    </script>
    <noscript>
        <div style="display:inline;">
            <img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/967658191/?value=0&amp;guid=ON&amp;script=0" />
        </div>
    </noscript>

    <!--End of Zopim Live Chat Script-->
    @RenderSection("OtherScripts", false)
</body>
</html>

PousseDeBambin/Views/Shared/_MainTabs.cshtml
<div class="menu">
    <ul>
        @{ string controller = ViewContext.Controller.ValueProvider
           .GetValue("controller").RawValue.ToString(); }
        @{ string action = ViewContext.Controller.ValueProvider
           .GetValue("action").RawValue.ToString(); }

        <li class="@("Home".Equals(controller) ? "active" : "" )">
            <a href="@Url.Action("Index", "Home")">Accueil</a>
        </li>
        <li class="@("Account".Equals(controller) ? "active" : "" )">
            @{
                if (HttpContext.Current.User.Identity.IsAuthenticated)
                {
                    <a href="@Url.Action("Creation", "List")">Je crée ma liste</a>
                }
                else
                {
                    <a href="@Url.Action("Creation", "List")">Je crée ma liste</a>
                }
            }

        </li>
        <a class="logo" href="@Url.Action("Index", "Home")"></a>

        <li class="@(("List".Equals(controller) && !"Search".Equals(action) && !"Manage".Equals(action)) ? "active" : "")">
            <a href="@Url.Action("Search", "List")">J'offre un cadeau</a>
        </li>
        <li class="@(("List".Equals(controller) && ("Search".Equals(action) || "Manage".Equals(action)))? "active" : "" )">
            <a href="@Url.Action("WhoAreWe", "Home")">Qui sommes-nous ?</a>
        </li>
    </ul>


</div>

PousseDeBambin/Views/Shared/_MessageBeta.cshtml
<div class="alert alert-success alert-dismissable text-beta">
    Pousse De Bambin vient de naître...et, comme tout être, va se perfectionner petit à petit. Ainsi
    <a href="mailto:community@poussedebambin.com?subject=Retour Pousse De Bambin&body=Bonjour," target="_blank" class="alert-link">contactez nous</a> pour faire votre retour ! Vous ferez des pousses heureuses !
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
</div>

PousseDeBambin/Views/Shared/_MoreFooter.cshtml
<!--<div id="texteFooter">
    <p>Pousse De Bambin est un site internet qui vous propose de créer votre liste de naissance et de la partager avec votre entourage, cela gratuitement et en toute simplicité !
    <br/>
        En France, il est de tradition d'offrir des cadeaux à la naissance d'un enfant, l'inconvénient, c'est souvent que l'on reçoit des cadeaux qu'on ne souhaite pas (la fameuse Sophie la Girafe), et/ou en plusieurs exemplaires (tout le monde veut offrir le doudou !).
    <br/>
        Nous avons décidé de rendre service aux futurs parents en leur permettant de créer leur liste d'envies. Dès qu'un cadeau que vous avez selctionné est fait, il est retiré de la liste de naissance et donc impossible de l'avoir en double ! Cela vous permet de gérer l'arrivée du bébé en sachant à l'avance ce que vous avez et ce dont vous aurez besoin
    </p>
</div>-->